f1 = open("file.txt","a+")
Name=input("Please enter name: ")
university=input("Please enter university: ")
f1.write("Name: "+(Name))
f1.write("university: "+(university))
printt(f2.read())
fw.close()
printt(f2.read())
